### ISSUE TITLE
Turkish Translation for Steam Overlay

### ISSUE THREAD

**Issue by Clompress** [otavepto/gbe_fork#124]
Greetings,
I made a Turkish translation for your Steam Emulator. You can download steam_overlay_translations.h file from [here](https://pixeldrain.com/u/BePxpHgX).
Thank you.

**Comment by Clompress** [comment]
Greetings again,
I just realized that I found a few mistakes in my translation, please excuse me. You can download the new translation [here](https://pixeldrain.com/u/xiTuNDmg).
Thank you.

**Comment by DogancanYr** [comment]
> Greetings again, I just realized that I found a few mistakes in my translation, please excuse me. You can download the new translation [here](https://pixeldrain.com/u/RDCu569s). Thank you.

I never realized that the Turkish translation was outdated. I'm glad you know these things.

**Comment by Clompress** [comment]
There is no wrong translation at the moment.  Thank you for adding it. Feel free to contact me if you see anything wrong with the translation.

**Comment by Clompress** [comment]
Greetings,
I have a request for translation. The achievement text appears as %Y-%m-%d at %H:%M:%S independent of the translation file. Is there any chance to integrate this into the translation file? I mean, it would be great if we could edit the word "at" directly from steam_overlay_translations.h without editing steam_overlay.cpp. That way we could set the year, day and month order as we want. It would be great if you could do that. I follow your work with impatience.
Thank you very much.

P.S: I also made a small correction in the translation, I would appreciate if you could add it. You can download the file [here](https://pixeldrain.com/u/kuQMxbom).

![Ekran Görüntüsü](https://github.com/otavepto/gbe_fork/assets/160234297/b5180e88-96b9-4a5b-a7f9-de99353d157e)
