### ISSUE TITLE
Days Gone Overlay Not Showing

### ISSUE THREAD

**Issue by Clompress** [otavepto/gbe_fork#125]
Greetings,
The game opens normally but when I press Shift+TAB the Overlay does not open. The interesting thing is that when I test it with the old version of the emulator ([release-2024_2_29](https://github.com/otavepto/gbe_fork/releases/tag/release-2024_2_29)) there is no problem. You can access the STEAM_LOG.txt file [here](https://pixeldrain.com/u/DdhJq9tD).
Thank you.

**Comment by gameclamp** [comment]
https://github.com/otavepto/gbe_fork/blob/dev/post_build/README.release.md#note-at-the-moment-this-feature-is-only-enabled-in-the-experimental-builds
 the overlay disable by default now.

**Comment by Clompress** [comment]
I know. I created enable_experimental_overlay.txt file in steam_settings folder but overlay is not working.

**Comment by Clompress** [comment]
I created the `overlay_hook_delay_sec.txt` file and entered the value 15 and the problem was solved. Thank you <3
