### ISSUE TITLE
dev notes with explanations for anything

### ISSUE THREAD

**Issue by otavepto** [otavepto/gbe_fork#150]
sharing knowledge enures others can do the same and build on it.

**Comment by Detanup01** [comment]
do you have an example for it?

**Comment by Detanup01** [comment]
Oh I would defenetly would check out, might just a .md files in here under the folder Knowledge or something to it.
I might well write something that how can you implement new interface version too

**Comment by Detanup01** [comment]
Since we already started this, I closing it
