### ISSUE TITLE
Is there any way to compile the fork using the old overlay (before the overlay used in Nerm)? constant Hook problems

### ISSUE THREAD

**Issue by Vlxst** [otavepto/gbe_fork#183]
I have this doubt, if you can help me with something... I will be grateful

**Comment by Detanup01** [comment]
https://github.com/otavepto/gbe_fork/releases/tag/release-2024_2_29
This is the last build before new overlay

**Comment by Vlxst** [comment]
> https://github.com/otavepto/gbe_fork/releases/tag/release-2024_2_29 This is the last build before new overlay

Yes, I would like to be able to compile the changes from the current version (excluding changes to the overlay) and add only significant changes to the GB code to this build, is that possible? I really appreciate the help

**Comment by Detanup01** [comment]
Closing it.
