### ISSUE TITLE
SteamQuery only works on the local network

### ISSUE THREAD

**Issue by UrbanSide** [otavepto/gbe_fork#226]
This fix for the game Soulmask opens Query but only from the local network + players experience an eternal connection timeout and the server is not visible in the list of games.
Can this be fixed somehow or not?

**Comment by UrbanSide** [comment]
My log file

[log.txt](https://github.com/user-attachments/files/15843827/log.txt)

**Comment by Detanup01** [comment]
disable_lan_only=1

**Comment by UrbanSide** [comment]
> configs.main.ini:
> 
> [main::connectivity] disable_lan_only=1
> 
> and will get others to connect and not lan only

where can I find this file?

**Comment by UrbanSide** [comment]
I found it, did it, and it seems to work. And as far as I understand, the official game still won’t have it in the list of servers?

**Comment by UrbanSide** [comment]
![image](https://github.com/otavepto/gbe_fork/assets/26259129/4cff09df-07db-4b80-b223-c4bbd5b6fb94)

**Comment by Detanup01** [comment]
No 
And ofc the official server not gonna do anything since the server doesn't send anything to steam, that's why hence the name, steam emulator. It doesn't connect to steam in any way

**Comment by UrbanSide** [comment]
> No 
> And ofc the official server not gonna do anything since the server doesn't send anything to steam, that's why hence the name, steam emulator. It doesn't connect to steam in any way

Well, the same steam ID can be obtained from the registry logically and the emulator is capable of this, I think.

**Comment by UrbanSide** [comment]
I can’t solve one more question. I wrote the game ID in steam_appid.txt in the steam_settings folder, I did the same for the client. But the client doesn’t see the server. Although the client has the server ip registered in steam_settings in custom_broadcasts.txt.

> No And ofc the official server not gonna do anything since the server doesn't send anything to steam, that's why hence the name, steam emulator. It doesn't connect to steam in any way
