### ISSUE TITLE
Bugs with the Overlay and Game Startup for Two Games

### ISSUE THREAD

**Issue by CHESIRE721** [otavepto/gbe_fork#239]
As the title says, I found three problems and prefer to report them together rather than create a separate topic for each one.

1. **Overlay Issue**:
    The first issue is connected with the overlay, which has a problem with how it displays the language of achievements in the LATAM language. For example, in Bloodstained: Ritual of the Night, the achievements are configured in LATAM Spanish, not standard Spanish. When configuring the emulator to the LATAM language, instead of showing the descriptions in Latin American Spanish, it directly uses the descriptions from the English language.

![Captura de pantalla 2024-06-24 175956](https://github.com/otavepto/gbe_fork/assets/64328889/272faa8b-7989-45f7-ab49-4a881ebb1321)

2. **WitchSpring R Issue**:
    The second problem is with the game WitchSpring R. When this game starts, it shows its logo but then stays on a black screen, preventing gameplay. I used the unmodified game data, only using the launcher. I will attach the game log.

3. **Fatermyth Issue**:
    The third problem is related to the game Fatermyth. This issue is quick to explain: the game starts, reaches the menu, and then automatically closes. This game does not generate a log when opened with the debug version of the emulator, so I had to use Mr. Goldberg's latest emulator version to generate the log.

I will attach the game logs for review. If these issues cannot be fixed, it's not a problem. Thank you in advance for your support of this fork.

[STEAM_LOG_bloodstained.txt](https://github.com/user-attachments/files/15962032/STEAM_LOG_bloodstained.txt)
[STEAM_LOG_Fatermyth.txt](https://github.com/user-attachments/files/15962033/STEAM_LOG_Fatermyth.txt)
[STEAM_LOG_WitchSpring R.txt](https://github.com/user-attachments/files/15962034/STEAM_LOG_WitchSpring.R.txt)

**Comment by CHESIRE721** [comment]
> Well, the game Fatermyth has an integrity check, you have to use cold client loader. Probably what happened is that you replaced the .dll, it didn't work, so you restored it and used cold client from the original emu.
> 
> img
> Try delaying the hook by setting this option
> 
> ```ini
> [overlay::general]
> # amount of time to wait before attempting to detect and hook the renderer (DirectX, OpenGL, etc...)
> # default=0
> hook_delay_sec=10
> ```
All the games were loaded with the steamclient64.dll version and Smart Steam Emu as the loader. Do not replace the steam_api64.dll of any game in order to generate the logs. (Use the latest version released, which is from 2024-06-21)

Now, for Fatermyth (2530420), even though I loaded it with ColdClient and configured the overlay as you mentioned, the game simply closes again after 3 seconds of being in the menu. I was able to generate the log with the latest version of the original Goldberg Emu, since the debug launcher of the release-2024_6_21 version does not generate the log.

**Comment by CHESIRE721** [comment]
For Fatermyth, I did what you recommended: used ColdClientLoader and changed the directory name. I configured it properly, but I still got the error where the game closes after 3 seconds in the menu. However, this time it did generate a log, which I will attach just in case.
[STEAM_LOG.txt](https://github.com/user-attachments/files/16006356/STEAM_LOG.txt)

**Comment by CHESIRE721** [comment]
Here's the translation to English:

I detected another problem, or rather, I discovered something while playing Final Fantasy IX. The game automatically deletes the steam_appid.txt file from its main folder, even if it is in the steam_settings folder. However, if I add a launcher that has the configuration outside the main folder, the game does not delete the steam_appid.txt file. 

But making this configuration causes the emulator not to correctly detect the game, preventing the overlay from rendering and also blocking achievements.

Now, the strange part is that if I replace the game's steam_api.dll/steam_api64.dll files (there are 4 in total since it is using Unity in a peculiar way) and then run the game launcher from steamclient_loader_x32.exe, the game manages to render the overlay. However, if I run the game directly from FF9_Launcher.exe, the emulator notifies that the game's AppID is not specified and will use ID 0 until the file is added.

I will attach the game log because it is very strange how FFIX interacts with the emulator. To make it work properly, I have to combine the emulator in its steam_api.dll/steam_api64.dll version with the steamclient.dll/steamclient64.dll version to make the game function correctly.
[STEAM_LOG.txt](https://github.com/user-attachments/files/16019404/STEAM_LOG.txt)

**Comment by mixa-pulemet** [comment]
Hello. Could you please advise about overlay in the game Halls of Torment. With the standard type of rendering (Vulkan) overlay does not work, but if you set the type of rendering OpengGL overlay works perfectly. Is it possible to make the overlay work with Vulkan? I attach 2 logs.
[STEAM_LOG_Vulkan.txt](https://github.com/user-attachments/files/16020573/STEAM_LOG_Vulkan.txt)
[STEAM_LOG_OpenGL.txt](https://github.com/user-attachments/files/16020575/STEAM_LOG_OpenGL.txt)

**Comment by CHESIRE721** [comment]
> Hello. Could you please advise about overlay in the game Halls of Torment. With the standard type of rendering (Vulkan) overlay does not work, but if you set the type of rendering OpengGL overlay works perfectly. Is it possible to make the overlay work with Vulkan? I attach 2 logs. [STEAM_LOG_Vulkan.txt](https://github.com/user-attachments/files/16020573/STEAM_LOG_Vulkan.txt) [STEAM_LOG_OpenGL.txt](https://github.com/user-attachments/files/16020575/STEAM_LOG_OpenGL.txt)

The game doesn't use Vulkan; it uses DirectX 12. The problem with the overlay not rendering and the game crashing is because the DX12 overlay seems to get overloaded when loading the images of the 310 achievements that need to be displayed in the list. However, OpenGL doesn't require as much load to render the achievement icons. That's why it works for you in OpenGL, but crashes and freezes in DX12.
[STEAM_LOG.txt](https://github.com/user-attachments/files/16023072/STEAM_LOG.txt)

**Comment by mixa-pulemet** [comment]
I'm pretty sure the game uses Vulkan after all. MSI Afterburner and Godot game engine says so. 
<details><summary>Halls of Torment screeshot</summary>
<p>
![Снимок экрана 2024-06-28 101653](https://github.com/otavepto/gbe_fork/assets/110778140/b96e22ed-c0e7-496f-9d12-c156e11ce32d)
</p>
</details>
And with DX12 rendering and 320 achievements in Sid Meier's Civilization VI the overlay works fine.
<details><summary>Sid Meier's Civilization VI screeshot</summary>
<p>
![Снимок экрана (294)](https://github.com/otavepto/gbe_fork/assets/110778140/d54db26d-86b1-4d38-b05c-af821b3f2eb0)
</p>
</details>

**Comment by mixa-pulemet** [comment]
I'm pretty sure the game uses Vulkan after all. MSI Afterburner and Godot game engine says so.
<details><summary>Halls of Torment screeshot</summary>
<p>

![Снимок экрана 2024-06-28 101653](https://github.com/otavepto/gbe_fork/assets/110778140/89d08e8e-7784-4576-b153-b2cf205fc610)


</p>
</details> 

And with DX12 rendering and 320 achievements in Sid Meier's Civilization VI the overlay works fine.

<details><summary>Sid Meier's Civilization VI screeshot</summary>
<p>

![Снимок экрана (294)](https://github.com/otavepto/gbe_fork/assets/110778140/377ef44a-823e-4211-82a8-49471c79dfaa)


</p>
</details>

**Comment by mixa-pulemet** [comment]
> > Hello. Could you please advise about overlay in the game Halls of Torment. With the standard type of rendering (Vulkan) overlay does not work, but if you set the type of rendering OpengGL overlay works perfectly. Is it possible to make the overlay work with Vulkan? I attach 2 logs. [STEAM_LOG_Vulkan.txt](https://github.com/user-attachments/files/16020573/STEAM_LOG_Vulkan.txt) [STEAM_LOG_OpenGL.txt](https://github.com/user-attachments/files/16020575/STEAM_LOG_OpenGL.txt)
> 
> The game doesn't use Vulkan; it uses DirectX 12. The problem with the overlay not rendering and the game crashing is because the DX12 overlay seems to get overloaded when loading the images of the 310 achievements that need to be displayed in the list. However, OpenGL doesn't require as much load to render the achievement icons. That's why it works for you in OpenGL, but crashes and freezes in DX12. [STEAM_LOG.txt](https://github.com/user-attachments/files/16023072/STEAM_LOG.txt)

I'm pretty sure the game uses Vulkan after all. MSI Afterburner and Godot game engine says so.

<details><summary>Halls of Torment screenshot</summary>
<p>

![Снимок экрана 2024-06-28 101653](https://github.com/otavepto/gbe_fork/assets/110778140/d09fb472-698d-4beb-aba4-89795cffae60)


</p>
</details> 

And with DX12 rendering and 320 achievements in Sid Meier's Civilization VI the overlay works fine.

<details><summary>Sid Meier's Civilization VI screenshot</summary>
<p>

![Снимок экрана (294)](https://github.com/otavepto/gbe_fork/assets/110778140/d0eca7af-ea44-4334-b320-16b9fe52b1a3)


</p>
</details>

**Comment by Detanup01** [comment]
Godot with any overlay not works if build as Forward +

**Comment by mixa-pulemet** [comment]
> As I said, and I reiterate, the game is using DX12 for the overlay, not Vulkan.

I don't mind that overlay uses DX12. I wrote about Vulkan because it's the default renderer type of the game and with it the overlay doesn't work for me, but works only if I run the game through OpenGL. Any suggestions on how to fix this or is it a problem with my hardware?

**Comment by CHESIRE721** [comment]
> > As I said, and I reiterate, the game is using DX12 for the overlay, not Vulkan.
> 
> I don't mind that overlay uses DX12. I wrote about Vulkan because it's the default renderer type of the game and with it the overlay doesn't work for me, but works only if I run the game through OpenGL. Any suggestions on how to fix this or is it a problem with my hardware?

I gave you the solution in the comment. Don't use MSI Afterburner, and the game will be able to render the emulator's overlay.

**Comment by mixa-pulemet** [comment]
> I gave you the solution in the comment. Don't use MSI Afterburner, and the game will be able to render the emulator's overlay.

Please don't write your "incredible" advice if there is nothing to help.

**Comment by CHESIRE721** [comment]
You’re right, it’s my fault for not explaining myself well, leaving an incomplete message that made this seem like an argument. Sorry about that. Regarding Final Fantasy IX, I will do what you mentioned to avoid unnecessarily cluttering this thread.

**Comment by CHESIRE721** [comment]
I just tested the PR build, and it correctly loads the language specified in supported_languages.txt, successfully loading the achievement language correctly.
![image](https://github.com/otavepto/gbe_fork/assets/64328889/cb229400-8e47-43b5-a555-aa3357527236)

**Comment by CHESIRE721** [comment]
> For the game WitchSpring R, the cold client loader setup works fine, just put all the loader files in a parent directory outside the game's root folder, and as usual steam_api(64).dll must be the original one.
> 
> ```ini
> [SteamClient]
> Exe=WitchSpring R\WitchSpringR.exe
> ExeRunDir=
> AppId=1958220
> ```
> 
> The game could also handle utf-8 paths properly
> 
> img
> ![image](https://private-user-images.githubusercontent.com/153766569/344425747-f2b2defb-cfbf-4f70-8c82-ffad0aba75ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2OTEwNjUsIm5iZiI6MTcxOTY5MDc2NSwicGF0aCI6Ii8xNTM3NjY1NjkvMzQ0NDI1NzQ3LWYyYjJkZWZiLWNmYmYtNGY3MC04YzgyLWZmYWQwYWJhNzVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxOTUyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTQ0MTM1NzA2YjI4OGYzM2RhZDE3M2MzNzI3YTFhODEwNjM3NzA2NWI1NWEzOGY4Y2Q0MTdjNzJkMTgyNWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R4Xx8X6c30_MjI2v5SpNGToWQISU4ZlfrhS0i2kYxog)

I tested the game WitchSpring R, but it still shows a black screen after the logo. I am using version 1.307, which generates this issue. Previous builds of the game did not have this problem.
>img
>![image](https://github.com/otavepto/gbe_fork/assets/64328889/42c78da9-dcc9-4ee6-814e-07d76f208b90)

**Comment by CHESIRE721** [comment]
> Github auto closes on merge, so I reopened again @CHESIRE721 When you have time please test the new linked PR #244

With the latest PR and the fixes you made, the game WitchSpring R no longer stays on a black screen; it now starts up correctly.
