### ISSUE TITLE
I am confused .

### ISSUE THREAD

**Issue by DogancanYr** [otavepto/gbe_fork#42]
Why is there steamclient64.dll in the experimental file?

I guess they don't work unless we use them with experimental steamclient.

**Comment by DogancanYr** [comment]
I couldn't find a game where only experimental_steamclient files worked. All games can be run by changing the steam_api(64).dll.
Can you tell me a game to try ?

**Comment by DogancanYr** [comment]
> I never copied it actually! You can skip at all together.

It was used in the Dave the Diver game, but I didn't understand how it worked.

**Comment by Detanup01** [comment]
Oh I had one game where is it specificly needed that file!
If the steam_api dll replacement not help then the client will probably gonna work. (not 100%! can be different how devs are used steam api.)

**Comment by DogancanYr** [comment]
> Oh I had one game where is it specificly needed that file! If the steam_api dll replacement not help then the client will probably gonna work. (not 100%! can be different how devs are used steam api.)

Greenluma or https://github.com/st2024/Steamtools/releases/tag/1.8 definitely works. They use Steam directly to run the games. Unfortunately they don't work for achievements or online.
