### ISSUE TITLE
No Achievement Icons in DX12 Overlay

### ISSUE THREAD

**Issue by ugurkahriman** [otavepto/gbe_fork#54]
I don't know if it's unique to The Last of Us Part I, but there are no achievement icons in the DX12 Overlay. It's also extremely laggy for some reason.

![Ekran görüntüsü 2024-01-31 234956](https://github.com/otavepto/gbe_fork/assets/140934014/deb5bdba-b76e-49e3-9956-fcbc6d3fb8b7)

**Comment by LuKeSt0rm** [comment]
Achievements icons are currently not compatible with DX12 API at the time of this post.

**Comment by ugurkahriman** [comment]
It works perfectly. Thank you for keeping this project alive.

![Ekran görüntüsü 2024-02-09 161747](https://github.com/otavepto/gbe_fork/assets/140934014/4e04f885-5c12-40c0-81d5-b943d4f39ddd)

**Comment by ugurkahriman** [comment]
Actually, I found another small bug, when you Alt+TAB in a DX12 game, the achievement icons disappear.

Befor Alt+TAB
![Ekran görüntüsü 2024-02-09 163838](https://github.com/otavepto/gbe_fork/assets/140934014/3a5cc673-c39a-4e92-8186-a37a6ba4a4c6)

After Alt+TAB
![Ekran görüntüsü 2024-02-09 163844](https://github.com/otavepto/gbe_fork/assets/140934014/b7a1cdcd-6c1d-404c-8631-38f982d5d211)

**Comment by ugurkahriman** [comment]
Thanks! It works perfectly even as it is. I hope this problem will be completely solved in the cleanest way soon.
