### ISSUE TITLE
games crash upon Achievement Watcher toast notification when disable_overlay.txt is enabled

### ISSUE THREAD

**Issue by turusudiro** [otavepto/gbe_fork#88]
tried with Speedrunners and Warriors Orochi 4 everytime achievement unlocked and a toast notification appear it will instantly crash the game. This issue occurs only when the 'disable_overlay.txt' file is present. However, using 'disable_overlay_achievement_notification.txt' resolves the problem.

**Comment by turusudiro** [comment]
I'm using the latest release. I dont test it yet using original emu, but where's the log exactly? im using ColdClientLoader.

**Comment by turusudiro** [comment]
This is exactly what happened when using disable_overlay.txt

https://github.com/otavepto/gbe_fork/assets/93848801/f84f6400-aad9-41bd-b1a1-5a4dcbffc805

And this is without disable_overlay.txt and with disable_overlay_achievement_notification.txt

https://github.com/otavepto/gbe_fork/assets/93848801/12013988-eb42-4cdf-9a78-83ff00e8ffaa

**Comment by turusudiro** [comment]
Unfortunately it still crash, also it doesnt create any log with https://github.com/otavepto/gbe_fork/actions/runs/8211307943 debug release? i've been looking in Steam folder, the ColdClientLoader folder and the games folder i cant find it anywhere...

**Comment by CHESIRE721** [comment]
@otavepto 
I got the game and generated the log so you can check the overlay problem when opening the game without the disable_overlay.txt file.
[STEAM_LOG.txt](https://github.com/otavepto/gbe_fork/files/14544970/STEAM_LOG.txt)

**Comment by turusudiro** [comment]
Hey, just find out that im not replace my old steamclient.dll with this release lol for some reason sorry.

> You have to use the debug build, it produces a file called `STEAM_LOG.txt`. I've posted a hotfix, I'd appreciate if you'd test it when you have time: https://github.com/otavepto/gbe_fork/actions/runs/8211307943
> 
> Once Github finishes, you'll be able to download the build, it takes ~20 min.

after using this release, the games worked fine with disable_overlay.txt and notification appear without crashing the game i guess its fixed.
